apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- update-tron-api.yaml
namespace: influx-apps
images:
- newName: bitfolio/update-tron-stats
  newTag: v0.0.1
- name: update-tron-stats
  newName: bitfolio/update-tron-stats
  newTag: v0.4
